/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#76014e",
        "inverse-primary": "#d3bbff",
        "surface-variant": "#ebdcff",
        "primary-fixed": "#ebddff",
        "surface-container": "#f4eaff",
        "on-surface": "#260059",
        "tertiary-fixed": "#ffdcc3",
        "primary": "#5300b7",
        "inverse-on-surface": "#f7edff",
        "on-primary-fixed": "#250059",
        "surface-container-low": "#f9f0ff",
        "primary-container": "#6d28d9",
        "on-tertiary-fixed": "#2f1500",
        "on-tertiary-container": "#ffc394",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#3d0026",
        "surface-container-highest": "#ebdcff",
        "on-surface-variant": "#4a4455",
        "on-primary-fixed-variant": "#5b00c5",
        "surface-bright": "#fef7ff",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#3f0689",
        "surface": "#fef7ff",
        "on-background": "#260059",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#ffafd3",
        "on-secondary": "#ffffff",
        "surface-dim": "#e4d2ff",
        "on-error": "#ffffff",
        "secondary-container": "#fc79bd",
        "primary-fixed-dim": "#d3bbff",
        "on-primary-container": "#dac5ff",
        "outline-variant": "#ccc3d7",
        "tertiary": "#653400",
        "outline": "#7b7486",
        "surface-tint": "#7331df",
        "tertiary-fixed-dim": "#ffb77d",
        "secondary": "#a43073",
        "on-tertiary-fixed-variant": "#6e3900",
        "on-primary": "#ffffff",
        "surface-container-high": "#f0e3ff",
        "tertiary-container": "#884800",
        "on-tertiary": "#ffffff",
        "background": "#fef7ff",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#85145a",
        "secondary-fixed": "#ffd8e7"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "margin-sm": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "gutter": "1.5rem",
        "gutter-sm": "1rem",
        "margin": "2rem"
      },
      fontFamily: {
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero": ["Playfair Display", "serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "price-headline": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero-mobile": ["Playfair Display", "serif"]
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "display-hero": ["52px", { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "price-headline": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "display-hero-mobile": ["34px", { lineHeight: "42px", letterSpacing: "-0.01em", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
}
